/**
 * @NApiVersion 2.1
 * @NScriptType plugintypeimpl
 */
define(
    [
        'N/runtime'
    ],
    (
        runtime
    ) => {
        const getVariables = () => {
            let respuesta = {};
            try {
                const mapObj = {
                    [ runtime.EnvType.PRODUCTION ]: {
                        customFormOppPotogas   : 265, // Oportunidad-Potogas
                        customFormOppCarb      : 264, // Oportunidad-Carburación
                        productgasLpId         : 4216,
                        publicoGeneralId       : 27041,
                        currency               : 1,// Pesos
                        tipoServicioEst        : 2,// Estacionario
                        tipoServicioCar        : 3,// Carburación
                        statusPedidoEntregado  : 3,// Entregado
                        statusPedidoAsignado   : 2,// Asignado
                        entityStatusConcretado : 13,// Concretado
                        tipoSgcWeb             : 1,// Web
                        urlSgcWeb              : "http://potogas.sgcweb.com.mx/ws/1094AEV2/v2/soap.php",
                        urlSgcWebLogin         : "http://potogas.sgcweb.com.mx/ws/1094AEV2/v2/soap.php/login",
                        urlSgcWebProcesar      : "http://potogas.sgcweb.com.mx/ws/1094AEV2/v2/soap.php/procesarPeticion",
                        urlSgcLocalDbUser      : "root",
                        urlSgcLocalDbPass      : "root",
                    },
                    [ runtime.EnvType.SANDBOX ]: {
                        customFormOppPotogas   : 305, // Oportunidad-Potogas
                        customFormOppCarb      : 307, // Oportunidad-Carburación
                        productgasLpId         : 4088,
                        publicoGeneralId       : 14508,
                        currency               : 1,// Pesos
                        tipoServicioEst        : 2,// Estacionario
                        tipoServicioCar        : 3,// Carburación
                        statusPedidoEntregado  : 3,// Entregado
                        statusPedidoAsignado   : 2,// Asignado
                        entityStatusConcretado : 13,// Concretado
                        tipoSgcWeb             : 1,// Web
                        urlSgcWeb              : "http://testpotogas.sgcweb.com.mx/ws/1094AEV2/v2/soap.php",
                        urlSgcWebLogin         : "http://testpotogas.sgcweb.com.mx/ws/1094AEV2/v2/soap.php/login",
                        urlSgcWebProcesar      : "http://testpotogas.sgcweb.com.mx/ws/1094AEV2/v2/soap.php/procesarPeticion",
                        urlSgcLocalDbUser      : "root",
                        urlSgcLocalDbPass      : "ROOT",
                    }
                }
                respuesta = mapObj[ runtime.envType ];
            } catch (error) {
                log.error(`error getVariables`, error);
            } finally {
                log.debug(`respuesta getVariables ${runtime.envType}`, respuesta);
                return respuesta;
            }
        }

          const drt_liquidacion = () => {
            let respuesta = {};
            try {
                const mapObj = {
                    [runtime.EnvType.PRODUCTION]: {
                        efectivo: 1,
                        prepagoBanorte: 2,
                        vale: 3,
                        cortesia: 4,
                        tarjetaCredito: 5,
                        tarjetaDebito: 6,
                        multiple: 7,
                        prepagoTransferencia: 8,
                        creditoCliente: 9,
                        reposicion: 10,
                        saldoAFavor: 11,
                        consumoInterno: 12,
                        prepagoBancomer: 13,
                        prepagoHSBC: 14,
                        prepagoBanamex: 15,
                        prepagoSantander: 16,
                        prepagoScotian: 17,
                        bonificacion: 18,
                        ticketCard: 19,
                        chequeBancomer: 20,
                        recirculacion: 21,
                        cancelado: 22,
                        relleno: 23,
                        transferencia: 24,
                        traspaso: 25,
                        chequeSantander: 26,
                        chequeScotian: 27,
                        chequeHSBC: 28,
                        chequeBanamex: 29,
                        chequeBanorte: 30,
                        tarjetaCreditoBancomer: 31,
                        tarjetaCreditoHSBC: 32,
                        tarjetaCreditoBanamex: 33,
                        tarjetaDebitoBanamex: 34,
                        tarjetaDebitoBancomer: 35,
                        tarjetaDebitoHSBC: 36,
                        publicoGeneral: 27041,
                        urlPago: "https://5298967.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=587&id=",
                        estatusRecibido: 2,
                        cilindro10: 4210,
                        cilindro20: 4211,
                        cilindro30: 4212,
                        cilindro45: 4213,
                        envase10: 4206,
                        envase20: 4207,
                        envase30: 4208,
                        envase45: 4209,
                        gasLP: 4216,
                    },
                    [runtime.EnvType.SANDBOX]: {
                        efectivo: 1,
                        prepagoBanorte: 2,
                        vale: 3,
                        cortesia: 4,
                        tarjetaCredito: 5,
                        tarjetaDebito: 6,
                        multiple: 7,
                        prepagoTransferencia: 8,
                        creditoCliente: 9,
                        reposicion: 10,
                        saldoAFavor: 11,
                        consumoInterno: 12,
                        prepagoBancomer: 13,
                        prepagoHSBC: 14,
                        prepagoBanamex: 15,
                        prepagoSantander: 16,
                        prepagoScotian: 17,
                        bonificacion: 18,
                        ticketCard: 19,
                        chequeBancomer: 20,
                        recirculacion: 21,
                        cancelado: 22,
                        relleno: 23,
                        transferencia: 24,
                        traspaso: 25,
                        chequeSantander: 26,
                        chequeScotian: 27,
                        chequeHSBC: 28,
                        chequeBanamex: 29,
                        chequeBanorte: 30,
                        publicoGeneral: 14508,
                        urlPago: "https://5298967-sb1.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=503&id=",
                        estatusRecibido: 2,
                        cilindro10: 4094,
                        cilindro20: 4095,
                        cilindro30: 4096,
                        cilindro45: 4602,
                        envase10: 4097,
                        envase20: 4099,
                        envase30: 4098,
                        envase45: 4604,
                        gasLP: 4088,
                    }
                }
                respuesta = mapObj[runtime.envType];
            } catch (error) {
                log.error(`error drt_liquidacion`, error);
            } finally {
                log.debug(`respuesta drt_liquidacion ${runtime.envType}`, respuesta);
                return respuesta;
            }
        }

        const drt_modulo_general = () => {
            let respuesta = {};
            try {
                const mapObj = {
                    [runtime.EnvType.PRODUCTION]: {
                        formularioCilindro: 177,
                        formularioEstacionario: 176,
                        estatus: 3,
                        equipoPipa: 1,
                        equipoCamion: 2,
                        equipoUtilitario: 3,
                        equipoOtro: 4,
                        formularioComp: 264,
                        servicioComp: 3,
                        tipoPagoComp: 2,
                        tipoPagoCreditoComp: 5,
                        entregadoEstadoPedido: 3,
                        articuloEstacionario: 2,
                        tipoPagoVariosComp: 7,
                        idArticuloDescuento: 4217,
                        articuloCilindro: 1,
                        articuloEnvase: 5,
                        cilindro10: 4210,
                        cilindro20: 4211,
                        cilindro30: 4212,
                        cilindro45: 4213,
                        articuloEstacionario: 2, 
                        unidad10: 12,
                        unidad20: 13,
                        unidad30: 14,
                        unidad45: 15,
                        plantillaDocumentoElectronico: 119,
                        metodoDeEnvio: 10,
                        paqueteMySuite: 2,
                        estatusEnCurso: 3,
                        formularioTrasladoCarburacion: 266,
                        gasLPUnidades: 4216,
                        efectivo: 1,
                        prepagoBanorte: 2,
                        vale: 3,
                        cortesia: 4,
                        tarjetaCredito: 5,
                        tarjetaDebito: 6,
                        multiple: 7,
                        prepagoTransferencia: 8,
                        creditoCliente: 9,
                        reposicion: 10,
                        saldoAFavor: 11,
                        consumoInterno: 12,
                        prepagoBancomer: 13,
                        prepagoHSBC: 14,
                        prepagoBanamex: 15,
                        prepagoSantander: 16,
                        prepagoScotian: 17,
                        bonificacion: 18,
                        ticketCard: 19,
                        chequeBancomer: 20,
                        recirculacion: 21,
                        cancelado: 22,
                        relleno: 23,
                        transferencia: 24,
                        traspaso: 25,
                        chequeSantander: 26,
                        chequeScotian: 27,
                        chequeHSBC: 28,
                        chequeBanamex: 29,
                        chequeBanorte: 30,
                        tarjetaCreditoBancomer: 31,
                        tarjetaCreditoHSBC: 32,
                        tarjetaCreditoBanamex: 33,
                        tarjetaDebitoBanamex: 34,
                        tarjetaDebitoBancomer: 35,
                        tarjetaDebitoHSBC: 36,
                        gasLP: 4216,
                        estatusPreliquidacion: 1,
                        estatusLiquidacion: 2,
                        estatusEjecutado: 3,
                        estatusFacturacion: 4,
                        publicoGeneral: 27041,
                        idPublicoGeneral: 27041,
                        urlPago: "https://5298967.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=587&id=",
                        estatusPendiente: 1,
                        estatusRecibido: 2,
                        estadoOpNegociacion: 11,
                        estadoOpCompra: 12,
                        estadoOpConcretado: 13,
                        estadoOpClienteConcretado: 18,
                        ventaServicioGas: 1,
                        ventaServicioCilindro: 2,
                        ventaServicio: 3,
                        envase10: 4206,
                        envase20: 4207,
                        envase30: 4208,
                        envase45: 4209,
                        formularioLiquidacion: 201,
                        limiteURL: 100,
                        formularioLiquidacionCilindro: 173,
                        estatusViajeLiquidacion: 2,
                        formularioFacturacionCilindro: 171,
                        estatusViajeEjecutado: 3,
                        urlCustomRecord: 'https://5298967.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=588&vehiculo=',
                        urlCustomRecordFormulario: '&formulario=',
                        estatusViajeConcluido: 1,
                        estatusFacturado: 4,
                        formularioLiquidacionEstacionario: 203,
                        formularioFacturacionEstacionario: 205,
                        idAlmacenGasolina: 1524,
                        idArticuloGasolina: 4605,
                        cuentaAjuste: 994,
                        tipoArticuloCilindro: 1,
                        cuentaAjusteInventario: 218,
                        formularioFacturaPTG: 308,
                        clienteTicketCar: 322997,
                        servicioCarburacion: 3,
                        publicoGeneralTXT: "Publico General",
                        clienteTicketCarTXT: "Ticket Card",
                        articuloServicio: 4218,
                        cuentaDefault: 2786,
                        subsidiariaCorpoGas: 22,
                        subsidiariaDistribuidora: 26,
                        subsidiariaSanLuis: 23,
                        formaDePagoDefault: 28,
                        servicioEstacionario: 2,
                        servicioCilindro: 1,
                        idArticuloServicio: 4217,
                        envaseCilindro: 5,
                        planta: 1505,
                        unidadLitros: 11,
                        envaseCilindro: 5,
                        formularioNotaCredito: 307,
                        vehiculoPipa: 1,
                        estatusFacturacionAnden: 4,
                        ubicacionAnden: 1502,
                        articuloChatarra: 4831,
                        efectivoAnden: 1,
                        tarjetaDebitoAnden: 2,
                        tarjetaCreditoAnden: 3,
                        chequeAnden: 4,
                        cortesiaAnden: 5,
                        valesTraspAnden: 6,
                        creditoClienteAnden: 7,
                        recirculacionAnden: 8,
                        efectivoPago: 1,
                        valePago: 3,
                        cortesiaPago: 4,
                        tarjetaCreditoPago: 5,
                        tarjetaDebitoPago: 6,
                        creditoClientePago: 9,
                        recirculacionPago: 21,
                        chequeBanamexPago: 29,
                        articuloBonificacion: 4218,
                        servicioViajeEspecial: 7,
                        efectivoId: 1,
                        prepagoBanorteId: 2,
                        valeId: 3,
                        cortesiaId: 4,
                        tarjetaCreditoId: 5,
                        tarjetaDebitoId: 6,
                        multipleId: 7,
                        prepagoTransferenciaId: 8,
                        creditoClienteId: 9,
                        reposicionId: 10,
                        saldoAFavorId: 11,
                        consumoInternoId: 12,
                        prepagoBancomerId: 13,
                        prepagoHSBCId: 14,
                        prepagoBanamexId: 15,
                        prepagoSantanderId: 16,
                        prepagoScotianId: 17,
                        bonificacionId: 18,
                        ticketCardId: 19,
                        chequeBancomerId: 20,
                        recirculacionId: 21,
                        canceladoId: 22,
                        rellenoId: 23,
                        transferenciaId: 24,
                        traspasoId: 25,
                        chequeSantanderId: 26,
                        chequeScotianId: 27,
                        chequeHSBCId: 28,
                        chequeBanamexId: 29,
                        chequeBanorteId: 30,
                        tarjetaCreditoBancomerId: 31,
                        tarjetaCreditoHSBCId: 32,
                        tarjetaCreditoBanamexId: 33,
                        tarjetaDebitoBanamexId: 34,
                        tarjetaDebitoBancomerId: 35,
                        tarjetaDebitoHSBCId: 36,
                        paqueteMySuite: 2,
                        plantillaDocumentoElectronico: 119,
                        metodoDeEnvio: 10,
                        formularioOrdenTraslado: 266,
                        clienteNoIdentificado: 27042,
                        cuenta: 2809,
                        formularioPago: 296,
                        estatusViejeEnCurso: 3,

                        condretado: 13,
                        pagoSGCContado: 1,
                        equipo: "2051",
                        formularioRecepcion: 270,
                        formularioOportunidadCarburacion: 264,
                        rfcGenerico: "XAXX010101000",
                        rfcPublicoGeneral: "AAA010101AAA",
                        estatusEtapa: 1,
                        estatusEtapaProcesado: 2,
                        descuentoPorcentaje: 1,
                        descuentoPeso: 2,
                        urlCilindros: 'https://5298967.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=585&whence=&vehiculo=',
                        urlEstacionarios: 'https://5298967.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=659&whence=&vehiculo=',
                        entregado: 3,
                        ventaLitro: 9,
                        formularioOportunidad: 265,
                        estatusProcesado: 2,
                        servicioCilindros: 1,
                        servicioEstacionarios: 2,
                        etapaProcesado: 2,
                        estatusEtapaCarga: 1,
                        estatusEtapaProcesado: 2,
                        estatusEtapaConciliado: 3,
                        formulario: 180,
                        clienteIndividual: 1,
                        estatusViajeEnCurso: 3,
                        turnoMatutino: 1,
                        turnoVespertino: 2,
                        articulo: 4216,
                        formularioTransferenciaInventario: 57,
                        precioValvulas: 100,
                        idCilindroChatarra: 4831,
                        valvula: 4670,
                        urlRegistroCliente: "https://5298967.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=645&planta=",
                        estadoConcretado: 13,
                        servicioVentanAnden: 5,
                        estadoEntregado: 3,
                        estatusServicioFacturado: 4,
                        formularioCustomRecord: 189,
                    },
                    [runtime.EnvType.SANDBOX]: {
                        formularioCilindro: 172,
                        formularioEstacionario: 173,
                        estatus: 3,
                        equipoPipa: 1,
                        equipoCamion: 2,
                        equipoUtilitario: 3,
                        equipoOtro: 4,
                        formularioComp: 307,
                        servicioComp: 3,
                        tipoPagoComp: 2,
                        tipoPagoCreditoComp: 5,
                        entregadoEstadoPedido: 3,
                        articuloEstacionario: 2,
                        tipoPagoVariosComp: 7,
                        idArticuloDescuento: 4528,
                        articuloCilindro: 1,
                        articuloEnvase: 5,
                        cilindro10: 4094,
                        cilindro20: 4095,
                        cilindro30: 4096,
                        cilindro45: 4602,
                        articuloEstacionario: 2,
                        unidad10: 24,
                        unidad20: 25,
                        unidad30: 26,
                        unidad45: 27,
                        plantillaDocumentoElectronico: 135,
                        metodoDeEnvio: 11,
                        paqueteMySuite: 2,
                        estatusEnCurso: 3,
                        formularioTrasladoCarburacion: 313,
                        gasLPUnidades: 4693,
                        efectivo: 1,
                        prepagoBanorte: 2,
                        vale: 3,
                        cortesia: 4,
                        tarjetaCredito: 5,
                        tarjetaDebito: 6,
                        multiple: 7,
                        prepagoTransferencia: 8,
                        creditoCliente: 9,
                        reposicion: 10,
                        saldoAFavor: 11,
                        consumoInterno: 12,
                        prepagoBancomer: 13,
                        prepagoHSBC: 14,
                        prepagoBanamex: 15,
                        prepagoSantander: 16,
                        prepagoScotian: 17,
                        bonificacion: 18,
                        ticketCard: 19,
                        chequeBancomer: 20,
                        recirculacion: 21,
                        cancelado: 22,
                        relleno: 23,
                        transferencia: 24,
                        traspaso: 25,
                        chequeSantander: 26,
                        chequeScotian: 27,
                        chequeHSBC: 28,
                        chequeBanamex: 29,
                        chequeBanorte: 30,
                        tarjetaCreditoBancomer: 31,
                        tarjetaCreditoHSBC: 32,
                        tarjetaCreditoBanamex: 33,
                        tarjetaDebitoBanamex: 34,
                        tarjetaDebitoBancomer: 35,
                        tarjetaDebitoHSBC: 36,
                        gasLP: 4088,
                        estatusPreliquidacion: 1,
                        estatusLiquidacion: 2,
                        estatusEjecutado: 3,
                        estatusFacturacion: 4,
                        publicoGeneral: 14508,
                        idPublicoGeneral: 14508,
                        urlPago: "https://5298967-sb1.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=503&id=",
                        estatusPendiente: 1,
                        estatusRecibido: 2,
                        estadoOpNegociacion: 11,
                        estadoOpCompra: 12,
                        estadoOpConcretado: 13,
                        estadoOpClienteConcretado: 18,
                        ventaServicioGas: 1,
                        ventaServicioCilindro: 2,
                        ventaServicio: 3,
                        envase10: 4097,
                        envase20: 4099,
                        envase30: 4098,
                        envase45: 4604,
                        formularioLiquidacion: 205,
                        limiteURL: 100,
                        formularioLiquidacionCilindro: 181,
                        estatusViajeLiquidacion: 2,
                        formularioFacturacionCilindro: 182,
                        estatusViajeEjecutado: 3,
                        urlCustomRecord: 'https://5298967-sb1.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=486&vehiculo=',
                        urlCustomRecordFormulario: '&formulario=',
                        estatusViajeConcluido: 1,
                        estatusFacturado: 4,
                        formularioLiquidacionEstacionario: 179,
                        formularioFacturacionEstacionario: 177,
                        idAlmacenGasolina: 1524,
                        idArticuloGasolina: 4605,
                        cuentaAjuste: 994,
                        tipoArticuloCilindro: 1,
                        cuentaAjusteInventario: 218,
                        formularioFacturaPTG: 286,
                        clienteTicketCar: 322997,
                        servicioCarburacion: 3,
                        publicoGeneralTXT: "Publico General",
                        clienteTicketCarTXT: "Ticket Card",
                        articuloServicio: 4832,
                        cuentaDefault: 2786,
                        subsidiariaCorpoGas: 22,
                        subsidiariaDistribuidora: 25,
                        subsidiariaSanLuis: 23,
                        formaDePagoDefault: 28,
                        servicioEstacionario: 2,
                        servicioCilindro: 1,
                        idArticuloServicio: 4528,
                        envaseCilindro: 5,
                        planta: 1142,
                        unidadLitros: 23,
                        envaseCilindro: 5,
                        formularioNotaCredito: 435,
                        vehiculoPipa: 1,
                        estatusFacturacionAnden: 4,
                        ubicacionAnden: 1142,
                        articuloChatarra: 4831,
                        efectivoAnden: 1,
                        tarjetaDebitoAnden: 2,
                        tarjetaCreditoAnden: 3,
                        chequeAnden: 4,
                        cortesiaAnden: 5,
                        valesTraspAnden: 6,
                        creditoClienteAnden: 7,
                        recirculacionAnden: 8,
                        efectivoPago: 1,
                        valePago: 3,
                        cortesiaPago: 4,
                        tarjetaCreditoPago: 5,
                        tarjetaDebitoPago: 6,
                        creditoClientePago: 9,
                        recirculacionPago: 21,
                        chequeBanamexPago: 29,
                        articuloBonificacion: 4832,
                        servicioViajeEspecial: 7,
                        efectivoId: 1,
                        prepagoBanorteId: 2,
                        valeId: 3,
                        cortesiaId: 4,
                        tarjetaCreditoId: 5,
                        tarjetaDebitoId: 6,
                        multipleId: 7,
                        prepagoTransferenciaId: 8,
                        creditoClienteId: 9,
                        reposicionId: 10,
                        saldoAFavorId: 11,
                        consumoInternoId: 12,
                        prepagoBancomerId: 13,
                        prepagoHSBCId: 14,
                        prepagoBanamexId: 15,
                        prepagoSantanderId: 16,
                        prepagoScotianId: 17,
                        bonificacionId: 18,
                        ticketCardId: 19,
                        chequeBancomerId: 20,
                        recirculacionId: 21,
                        canceladoId: 22,
                        rellenoId: 23,
                        transferenciaId: 24,
                        traspasoId: 25,
                        chequeSantanderId: 26,
                        chequeScotianId: 27,
                        chequeHSBCId: 28,
                        chequeBanamexId: 29,
                        chequeBanorteId: 30,
                        tarjetaCreditoBancomerId: 31,
                        tarjetaCreditoHSBCId: 32,
                        tarjetaCreditoBanamexId: 33,
                        tarjetaDebitoBanamexId: 34,
                        tarjetaDebitoBancomerId: 35,
                        tarjetaDebitoHSBCId: 36,
                        paqueteMySuite: 2,
                        plantillaDocumentoElectronico: 135,
                        metodoDeEnvio: 11,
                        formularioOrdenTraslado: 313,
                        clienteNoIdentificado: 322141,
                        cuenta: 2809,
                        formularioPago: 70,
                        estatusViejeEnCurso: 3,

                        condretado: 13,
                        pagoSGCContado: 1,
                        equipo: "2051",
                        formularioRecepcion: 258,
                        formularioOportunidadCarburacion: 307,
                        rfcGenerico: "XAXX010101000",
                        rfcPublicoGeneral: "AAA010101AAA",
                        estatusEtapa: 1,
                        estatusEtapaProcesado: 2,
                        descuentoPorcentaje: 1,
                        descuentoPeso: 2,
                        urlCilindros: 'https://5298967-sb1.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=497&whence=&vehiculo=',
                        urlEstacionarios: 'https://5298967-sb1.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=495&whence=&vehiculo=',
                        entregado: 3,
                        ventaLitro: 9,
                        formularioOportunidad: 305,
                        estatusProcesado: 2,
                        servicioCilindros: 1,
                        servicioEstacionarios: 2,
                        etapaProcesado: 2,
                        estatusEtapaCarga: 1,
                        estatusEtapaProcesado: 2,
                        estatusEtapaConciliado: 3,
                        formulario: 194,
                        clienteIndividual: 1,
                        estatusViajeEnCurso: 3,
                        turnoMatutino: 1,
                        turnoVespertino: 2,
                        articulo: 4088,
                        formularioTransferenciaInventario: 306,
                        precioValvulas: 100,
                        idCilindroChatarra: 4831,
                        valvula: 4670,
                        urlRegistroCliente: "https://5298967-sb1.app.netsuite.com/app/common/custom/custrecordentry.nl?rectype=1070&planta=",
                        estadoConcretado: 13,
                        servicioVentanAnden: 5,
                        estadoEntregado: 3,
                        estatusServicioFacturado: 4,
                        formularioCustomRecord: 324,
                    }
                }
                respuesta = mapObj[runtime.envType];
            } catch (error) {
                log.error(`error drt_modulo_general`, error);
            } finally {
                log.debug(`respuesta drt_modulo_general ${runtime.envType}`, respuesta);
                return respuesta;
            }
        }

        return {
            drt_liquidacion,
            getVariables,
            drt_modulo_general
        };

    });
